version: "3.8"

services:
  nginx:
    image: nginx:latest
    env_file:
      - ${ENV_FILE} # environnement dynamique (dev/prod)
    container_name: nginx-proxy-${CICD_ENV}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CICD_DIR}/${CICD_ENV}/nginx/conf.d:/etc/nginx/conf.d
      - ${CICD_DIR}/${CICD_ENV}/nginx/certs:/etc/nginx/certs
    depends_on:
      - gitlab
      - sonarqube
    networks:
      - gitlab-net
  gitlab:
    image: gitlab/gitlab-ce:latest
    env_file:
      - ${ENV_FILE} # environnement dynamique (dev/prod)
    container_name: gitlab-ce-${CICD_ENV}
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOSTNAME}/gitlab-${CICD_ENV}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - ${CICD_DIR}/${CICD_ENV}/gitlab/config:/etc/gitlab
      - ${CICD_DIR}/${CICD_ENV}/gitlab/logs:/var/log/gitlab
      - ${CICD_DIR}/${CICD_ENV}/gitlab/data:/var/opt/gitlab
    networks:
      gitlab-net:
        aliases:
          - gitlab-ce
          - ${GITLAB_HOSTNAME}

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    env_file:
      - ${ENV_FILE} # environnement dynamique (dev/prod)
    container_name: gitlab-runner-${CICD_ENV}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CICD_DIR}/${CICD_ENV}/gitlab-runner/config:/etc/gitlab-runner
    networks:
      - gitlab-net

  sonarqube:
    image: sonarqube:community
    env_file:
      - ${ENV_FILE}
    container_name: sonarqube-ce-${CICD_ENV}
    restart: always
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Xms512m -Xmx512m
      - SONARQUBE_JDBC_USERNAME=${SONAR_DB_USER}
      - SONARQUBE_JDBC_PASSWORD=${SONAR_DB_PASS}
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:${SONAR_DB_PORT_INTERNAL}/${SONAR_DB_NAME}
    ports:
      - "${SONARQUBE_HTTP_PORT}:9000"
    volumes:
      - ${CICD_DIR}/${CICD_ENV}/sonarqube/config:/opt/sonarqube/conf
      - ${CICD_DIR}/${CICD_ENV}/sonarqube/data:/opt/sonarqube/data
      - ${CICD_DIR}/${CICD_ENV}/sonarqube/extensions:/opt/sonarqube/extensions
      - ${CICD_DIR}/${CICD_ENV}/sonarqube/logs:/opt/sonarqube/logs
    depends_on:
      - sonarqube-db
    networks:
      - gitlab-net

  sonarqube-db:
    image: postgres:13
    env_file:
      - ${ENV_FILE}
    container_name: sonarqube-db-${CICD_ENV}
    restart: always
    environment:
      - POSTGRES_USER=${SONAR_DB_USER}
      - POSTGRES_PASSWORD=${SONAR_DB_PASS}
      - POSTGRES_DB=${SONAR_DB_NAME}
    ports:
      - "${SONAR_DB_PORT_EXTERNAL}:5432"
    volumes:
      - ${CICD_DIR}/${CICD_ENV}/sonarqube/postgres:/var/lib/postgresql/data
    networks:
      - gitlab-net

  nexus:
    image: sonatype/nexus3:latest
    env_file:
      - ${ENV_FILE}
    container_name: nexus-${CICD_ENV}
    restart: always
    ports:
      - "${NEXUS_HTTP_PORT}:8081"
    volumes:
      - ${CICD_DIR}/${CICD_ENV}/nexus/data:/nexus-data
    networks:
      - gitlab-net

networks:
  gitlab-net:
    name: gitlab-net-${CICD_ENV}
    driver: bridge
